kotlin.version=2.3.20
ktor.version=3.4.3
kotlin.wrappers.version=2026.4.4
kotlinx.html.version=0.11.0
kotlin.daemon.jvmargs=-Xmx8G
kotlinx.serialization.version=1.8.0
modName=WebCTC
modId=webctc
modGroup=org.webctc
useModGroupForPublishing=false
autoUpdateBuildScript=false
minecraftVersion=1.7.10
forgeVersion=10.13.4.1614-1.7.10
channel=stable
mappingsVersion=12
remoteMappings=https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName=Developer
enableModernJavaSyntax=false
enableGenericInjection=true
includeWellKnownRepositories=true
usesMavenPublishing=false
usesShadowedDependencies=true
minimizeShadowedDependencies=true
relocateShadowedDependencies=true
disableSpotless=true
gtnh.modules.ideIntegration=false
